#!/bin/bash
pip3 install -r requirements.txt
cd ./Data\ Processing
./extract_tar_file_script
python3 clean_comma_errors.py
python3 csv_to_pickle.py
python3 convert_to_feature_sequences_cw.py
python3 convert_to_feature_sequences_ow.py
rm -rf ../hp131_cw
rm -rf ../hp131_ow
